/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fcf9f8",
        "tertiary": "#006275",
        "inverse-surface": "#303030",
        "on-tertiary-fixed": "#001f27",
        "secondary-fixed": "#d6e3fb",
        "on-primary-fixed": "#001849",
        "surface-container-high": "#eae7e7",
        "primary": "#0050cb",
        "secondary": "#525f73",
        "on-primary": "#ffffff",
        "outline-variant": "rgba(194, 198, 216, 0.15)",
        "surface-tint": "#0054d6",
        "inverse-primary": "#b3c5ff",
        "tertiary-fixed-dim": "#48d7f9",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#004e5d",
        "on-surface-variant": "#424656",
        "on-tertiary-container": "#eefaff",
        "on-secondary": "#ffffff",
        "background": "#fcf9f8",
        "surface": "#fcf9f8",
        "primary-container": "#0066ff",
        "on-secondary-fixed": "#0f1c2d",
        "on-error": "#ffffff",
        "outline": "#727687",
        "surface-variant": "#e5e2e1",
        "on-secondary-fixed-variant": "#3b485a",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#b3c5ff",
        "surface-dim": "#dcd9d9",
        "secondary-container": "#d6e3fb",
        "surface-container-highest": "#e5e2e1",
        "on-background": "#1b1b1b",
        "on-secondary-container": "#586579",
        "surface-container-low": "#f6f3f2",
        "on-primary-container": "#f8f7ff",
        "primary-fixed": "#dae1ff",
        "on-primary-fixed-variant": "#003fa4",
        "on-error-container": "#93000a",
        "tertiary-container": "#007d94",
        "surface-container": "#f0eded",
        "inverse-on-surface": "#f3f0ef",
        "secondary-fixed-dim": "#bac7de",
        "on-surface": "#1b1b1b",
        "tertiary-fixed": "#afecff",
        "textMain": '#1A1A1A',
        "textMuted": '#666666',
        "border": '#E0E0E0',
      },
      fontFamily: {
        sans: ["'Jomolhari'", 'serif'],
        "headline": ["'Jomolhari'", 'serif'],
        "body": ["'Jomolhari'", 'serif'],
        "label": ["'Jomolhari'", 'serif']
      }
    },
  },
  plugins: [],
}
